jwt:
  token: "2iK9Z9QtmCt2MLLFp6xcvpUaUfw6jkDpZ9Rv8VxN"
debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_test
    username: root
    password: ee35jeCAMqAgtdC7
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: 'update'
    database: "mysql"
server:
  error:
    whitelabel:
      enabled: false