jwt:
  secret: "fmXwgeC9Lge2aT3TMaWXcvf94*Vn!3V84Q$cqq$93&osri^4#vNSsoUJ#nh^hL^^MsN!t&4c4TWMu%&tgY"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: ee35jeCAMqAgtdC7
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: "mysql"
server:
  error:
    whitelabel:
      enabled: false
springdoc:
  api-docs:
    path: "/v1/api-docs"
  swagger-ui:
    path: "/v1/docs"

zarinpal:
  mode: "normal"
  sandbox-request-payment-url: "https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
  sandbox-verify-payment-url: "https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
  sandbox-start-payment-url: "https://sandbox.zarinpal.com/pg/StartPay/"

  request-payment-url: "https://api.zarinpal.com/pg/v4/payment/request.json"
  verify-payment-url: "https://api.zarinpal.com/pg/v4/payment/verify.json"
  start-payment-url: "https://zarinpal.com/pg/StartPay/"

  merchant_id: "5522d245-848d-4c85-8d36-e0ee00b8a149"
