spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: ee35jeCAMqAgtdC7
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: "mysql"
