spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: ee35jeCAMqAgtdC7
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: "mysql"
