jwt:
  secret: "fmXwgeC9Lge2aT3TMaWXcvf94*Vn!3V84Q$cqq$93&osri^4#vNSsoUJ#nh^hL^^MsN!t&4c4TWMu%&tgY"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: ee35jeCAMqAgtdC7
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: "mysql"
server:
  error:
    whitelabel:
      enabled: false